### PR TITLE
Re-implementations and fixing some tests

### PR DESCRIPTION
**Pull request by git-toni**

### CODE REVIEW

**Comment by bebraw** [comment]
Do you think we are good to go? I don't mind publishing the first version. I can set it up so that you can push releases too.

**Comment by git-toni** [comment]
Except the `README`, which I will try to finish tomorrow, I think so yes. Oh and the `byArrowKeys` thing, that's not even thought of in here; but that was the point, wasn't it?

**Comment by bebraw** [comment]
We can leave `byArrowKeys` to its old place, yeah.

**Comment by git-toni** [comment]
Readme finished

**Comment by bebraw** [comment]
@git-toni Awesome. I published the first release and added you as an owner to the npm project so you can publish fixes too.

**Comment by git-toni** [comment]
Great! Future possible additions that come to mind:
- Func to deal with pagination ( eg. page 1 of rows, given a X rows/page)
- Querying by name, by column, by both, etc.
- Sorting by column/attrib
- Add/Delete rows

I know this is all implemented in Reactabular, but maybe it's a good idea to separate it from the core? Just wondering.

**Comment by bebraw** [comment]
Yeah, separation is the long term plan. We'll end up with `searchtabular` and `treetabular` at least to keep up with the naming. Sorting is a good candidate too. Ideally the main project should contain minimal amount of logic I think.

Now that I integrated `searchtabular` to the main project, `reactabular-select` feels a little weird. It's just one React related function. But I guess that will grow.

When it comes to pagination, I have [segmentize](https://www.npmjs.com/package/segmentize) for handling that. There is not row related logic, though. Maybe `segmentize.rows` or so would fit there.

**Comment by git-toni** [comment]
Indeed, I forgot about those! Ok it's covered then :)

**Pull request merged**
